version: '3'
services:
  db:
    image: postgres
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: test_app
    command: aerich upgrade
    ports:
      - "3003:8000"
    depends_on:
      - db
      - redis