version: '3'
services:
  db:
    image: postgres
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: test_app
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
  admin:
    build:
        context: ./fastapi-admin
        dockerfile: Dockerfile
    restart: always
    env_file: .env-non-dev
    network_mode: host
    image: fastapi-admin
    command: uvicorn examples.main:app_ --port 8000 --host 0.0.0.0
    depends_on:
      - db
      - redis
      - app